server:
  port: 8090
spring:
  profiles:
    active: dev
    include: secret
  jackson:
    serialization:
      fail-on-empty-beans: false
  threads:
    virtual:
      enabled: true
  datasource:
#    url: jdbc:mysql://localhost:3306/spring_boot_kafka
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:./db;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    open-in-view: false
logging:
  level:
    com.example.springbootkafka: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE